In [1]:
import pandas as pd
import smartclean as sc

In [13]:
# Load data
df = sc.read(r"C:\Users\David\Desktop\Models\smartclean-root\docs\titanic.csv")
print("Original shape:", df.shape)
print("\nFirst look:")
print(df.head())
print("\nMissing values:")
print(df.isna().sum())

Original shape: (891, 12)

First look:
   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0

   Parch            Ticket     Fare Cabin Embarked
0      0         A/5 21171   7.2500   NaN        S
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250   NaN        S
3      0            113803  53.1000  C123        S
4      0            373450   8.0500   NaN        S

Missing values:
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [14]:
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [16]:
# Profile the dataset
print("\n")
result = sc.profile(df)
print(result.summary())

Dataset Profile
========================================
Rows               : 891
Columns            : 12
Duplicate rows     : 0

Column               dtype           missing   missing%   outliers
------------------------------------------------------------------
PassengerId          numeric               0      0.00%          0
Survived             numeric               0      0.00%          0
Pclass               numeric               0      0.00%          0
Name                 text                  0      0.00%          0
Sex                  categorical           0      0.00%          0
Age                  numeric             177     19.87%         11
SibSp                numeric               0      0.00%         46
Parch                numeric               0      0.00%          0
Ticket               categorical           0      0.00%          0
Fare                 numeric               0      0.00%        116
Cabin                categorical         687     77.10%          0
Embarked             categorical           2      0.22%          0

In [13]:
# Auto clean
print("\n" + "="*60)
print("AUTO CLEAN")
print("="*60)
clean_df, report = sc.auto_clean(df, return_report=True)
report.summary()

============================================================
AUTO CLEAN
============================================================

C:\Users\David\Desktop\Models\smartclean-root\src\smartclean\profiler.py:111: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(sample.head(50), errors="raise")
C:\Users\David\Desktop\Models\smartclean-root\src\smartclean\profiler.py:111: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(sample.head(50), errors="raise")
C:\Users\David\Desktop\Models\smartclean-root\src\smartclean\profiler.py:111: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(sample.head(50), errors="raise")
C:\Users\David\Desktop\Models\smartclean-root\src\smartclean\profiler.py:111: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(sample.head(50), errors="raise")
C:\Users\David\Desktop\Models\smartclean-root\src\smartclean\profiler.py:111: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(sample.head(50), errors="raise")
C:\Users\David\Desktop\Models\smartclean-root\src\smartclean\profiler.py:111: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(sample.head(50), errors="raise")
C:\Users\David\Desktop\Models\smartclean-root\src\smartclean\profiler.py:111: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(sample.head(50), errors="raise")
C:\Users\David\Desktop\Models\smartclean-root\src\smartclean\profiler.py:111: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(sample.head(50), errors="raise")
C:\Users\David\Desktop\Models\smartclean-root\src\smartclean\profiler.py:111: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(sample.head(50), errors="raise")
C:\Users\David\Desktop\Models\smartclean-root\src\smartclean\profiler.py:111: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(sample.head(50), errors="raise")
C:\Users\David\Desktop\Models\smartclean-root\src\smartclean\profiler.py:111: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(sample.head(50), errors="raise")
C:\Users\David\Desktop\Models\smartclean-root\src\smartclean\profiler.py:111: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(sample.head(50), errors="raise")
C:\Users\David\Desktop\Models\smartclean-root\src\smartclean\profiler.py:111: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(sample.head(50), errors="raise")
C:\Users\David\Desktop\Models\smartclean-root\src\smartclean\profiler.py:111: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(sample.head(50), errors="raise")
C:\Users\David\Desktop\Models\smartclean-root\src\smartclean\profiler.py:111: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(sample.head(50), errors="raise")
C:\Users\David\Desktop\Models\smartclean-root\src\smartclean\profiler.py:111: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(sample.head(50), errors="raise")
C:\Users\David\Desktop\Models\smartclean-root\src\smartclean\profiler.py:111: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(sample.head(50), errors="raise")
C:\Users\David\Desktop\Models\smartclean-root\src\smartclean\profiler.py:111: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(sample.head(50), errors="raise")
C:\Users\David\Desktop\Models\smartclean-root\src\smartclean\profiler.py:111: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(sample.head(50), errors="raise")
C:\Users\David\Desktop\Models\smartclean-root\src\smartclean\profiler.py:111: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(sample.head(50), errors="raise")
C:\Users\David\Desktop\Models\smartclean-root\src\smartclean\profiler.py:111: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(sample.head(50), errors="raise")
C:\Users\David\Desktop\Models\smartclean-root\src\smartclean\profiler.py:111: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(sample.head(50), errors="raise")
C:\Users\David\Desktop\Models\smartclean-root\src\smartclean\profiler.py:111: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(sample.head(50), errors="raise")
C:\Users\David\Desktop\Models\smartclean-root\src\smartclean\profiler.py:111: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(sample.head(50), errors="raise")
C:\Users\David\Desktop\Models\smartclean-root\src\smartclean\profiler.py:111: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(sample.head(50), errors="raise")

══════════════════════════════════════════════
      SmartClean — Cleaning Summary
══════════════════════════════════════════════
  Columns renamed             :   12
    PassengerId  →  passengerid
    Survived  →  survived
    Pclass  →  pclass
    Name  →  name
    Sex  →  sex
    Age  →  age
    SibSp  →  sibsp
    Parch  →  parch
    Ticket  →  ticket
    Fare  →  fare
    Cabin  →  cabin
    Embarked  →  embarked
  Missing values filled       :  866
    age  (177 values — median)
    cabin  (687 values — mode)
    embarked  (2 values — mode)
  Text columns cleaned        :    3
    name, sex, ticket
  Outliers handled            :  441
    age  (66 — iqr, cap)
    sibsp  (46 — iqr, cap)
    parch  (213 — iqr, cap)
    fare  (116 — iqr, cap)
══════════════════════════════════════════════

In [16]:
# ── 4. Inspect the result ────────────────────────────────────────────────────
print("Clean shape:", clean_df.shape)
print("\nClean columns:", list(clean_df.columns))
print("\nMissing values after cleaning:\n")
print(clean_df.isna().sum())

Clean shape: (891, 12)

Clean columns: ['passengerid', 'survived', 'pclass', 'name', 'sex', 'age', 'sibsp', 'parch', 'ticket', 'fare', 'cabin', 'embarked']

Missing values after cleaning:

passengerid    0
survived       0
pclass         0
name           0
sex            0
age            0
sibsp          0
parch          0
ticket         0
fare           0
cabin          0
embarked       0
dtype: int64

In [17]:
clean_df.head(10)

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",Male,22.0,1.0,0,A/5 21171,7.2500,B96 B98,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Female,38.0,1.0,0,Pc 17599,65.6344,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",Female,26.0,0.0,0,Ston/O2. 3101282,7.9250,B96 B98,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",Female,35.0,1.0,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",Male,35.0,0.0,0,373450,8.0500,B96 B98,S
5,6,0,3,"Moran, Mr. James",Male,28.0,0.0,0,330877,8.4583,B96 B98,Q
6,7,0,1,"Mccarthy, Mr. Timothy J",Male,54.0,0.0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",Male,2.5,2.5,0,349909,21.0750,B96 B98,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",Female,27.0,0.0,0,347742,11.1333,B96 B98,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",Female,14.0,1.0,0,237736,30.0708,B96 B98,C

In [20]:
# 5. Manual API
print("\n" + "="*60)
print("MANUAL CHAINED API")
print("="*60)
cleaner = sc.Cleaner(df)
manual_df = (
    cleaner
    .clean_columns()
    .fix_types()
    .handle_missing()
    .remove_duplicates()
    .clean_text()
    .remove_outliers()
    .output()
)
cleaner.get_report().summary()
print("Manual clean shape:", manual_df.shape)

============================================================
MANUAL CHAINED API
============================================================

C:\Users\David\Desktop\Models\smartclean-root\src\smartclean\profiler.py:111: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(sample.head(50), errors="raise")
C:\Users\David\Desktop\Models\smartclean-root\src\smartclean\profiler.py:111: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(sample.head(50), errors="raise")
C:\Users\David\Desktop\Models\smartclean-root\src\smartclean\profiler.py:111: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(sample.head(50), errors="raise")
C:\Users\David\Desktop\Models\smartclean-root\src\smartclean\profiler.py:111: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(sample.head(50), errors="raise")
C:\Users\David\Desktop\Models\smartclean-root\src\smartclean\profiler.py:111: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(sample.head(50), errors="raise")
C:\Users\David\Desktop\Models\smartclean-root\src\smartclean\profiler.py:111: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(sample.head(50), errors="raise")
C:\Users\David\Desktop\Models\smartclean-root\src\smartclean\profiler.py:111: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(sample.head(50), errors="raise")
C:\Users\David\Desktop\Models\smartclean-root\src\smartclean\profiler.py:111: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(sample.head(50), errors="raise")
C:\Users\David\Desktop\Models\smartclean-root\src\smartclean\profiler.py:111: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(sample.head(50), errors="raise")
C:\Users\David\Desktop\Models\smartclean-root\src\smartclean\profiler.py:111: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(sample.head(50), errors="raise")
C:\Users\David\Desktop\Models\smartclean-root\src\smartclean\profiler.py:111: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(sample.head(50), errors="raise")
C:\Users\David\Desktop\Models\smartclean-root\src\smartclean\profiler.py:111: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(sample.head(50), errors="raise")
C:\Users\David\Desktop\Models\smartclean-root\src\smartclean\profiler.py:111: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(sample.head(50), errors="raise")
C:\Users\David\Desktop\Models\smartclean-root\src\smartclean\profiler.py:111: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(sample.head(50), errors="raise")
C:\Users\David\Desktop\Models\smartclean-root\src\smartclean\profiler.py:111: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(sample.head(50), errors="raise")

══════════════════════════════════════════════
      SmartClean — Cleaning Summary
══════════════════════════════════════════════
  Columns renamed             :   12
    PassengerId  →  passengerid
    Survived  →  survived
    Pclass  →  pclass
    Name  →  name
    Sex  →  sex
    Age  →  age
    SibSp  →  sibsp
    Parch  →  parch
    Ticket  →  ticket
    Fare  →  fare
    Cabin  →  cabin
    Embarked  →  embarked
  Missing values filled       :  866
    age  (177 values — median)
    cabin  (687 values — mode)
    embarked  (2 values — mode)
  Text columns cleaned        :    3
    name, sex, ticket
  Outliers handled            :  441
    age  (66 — iqr, cap)
    sibsp  (46 — iqr, cap)
    parch  (213 — iqr, cap)
    fare  (116 — iqr, cap)
══════════════════════════════════════════════

Manual clean shape: (891, 12)